version: '3.8'

services:
  db:
    image: mysql:5.7
    restart: always
    container_name: db
    ports:
      - "3307:3306"
    environment:
      MYSQL_DATABASE: payhere
      MYSQL_USER: user
      MYSQL_PASSWORD: password
      MYSQL_ROOT_PASSWORD: rootpass

  web:
    build: .
    ports:
      - "8000:8000"
    environment:
      - MYSQL_DATABASE=payhere 
      - MYSQL_USER=user 
      - MYSQL_PASSWORD=password 
    depends_on:
      - db