# Generated by Django 4.2 on 2023-04-24 07:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("caffe", "0001_initial"),
    ]

    operations = [
        migrations.RenameModel(old_name="AdminUser", new_name="Seller",),
    ]
